export type VerbModel = [string, [string, string, string]];

export const VERBS = [
  ['бути', ['be', 'was/were', 'been']],
  ['ставати', ['become', 'became', 'become']],
  ['починати', ['begin', 'began', 'begun']],
  ['ламати', ['break', 'broke', 'broken']],
  ['приносити', ['bring', 'brought', 'brought']],
  ['будувати', ['build', 'built', 'built']],
  ['купувати', ['buy', 'bought', 'bought']],
  ['могти', ['can', 'could', 'been able']],
  ['ловити', ['catch', 'caught', 'caught']],
  ['вибирати', ['choose', 'chose', 'chosen']],
  ['приходити', ['come', 'came', 'come']],
  ['коштувати', ['cost', 'cost', 'cost']],
  ['вирізати', ['cut', 'cut', 'cut']],
  ['робити', ['do', 'did', 'done']],
  ['пити', ['drink', 'drank', 'drunk']],
  ['їздити ::🚗::', ['drive', 'drove', 'driven']],
  ['їсти', ['eat', 'ate', 'eaten']],
  ['падати', ['fall', 'fell', 'fallen']],
  ['відчувати', ['feel', 'felt', 'felt']],
  ['боротися', ['fight', 'fought', 'fought']],
  ['знаходити', ['find', 'found', 'found']],
  ['літати', ['fly', 'flew', 'flown']],
  ['забувати', ['forget', 'forgot', 'forgotten']],
  ['отримувати', ['get', 'got', 'got']],
  ['давати', ['give', 'gave', 'given']],
  ['йти', ['go', 'went', 'gone']],
  ['рости', ['grow', 'grew', 'grown']],
  ['мати', ['have', 'had', 'had']],
  ['чути', ['hear', 'heard', 'heard']],
  ['бити', ['hit', 'hit', 'hit']],
  ['тримати', ['keep', 'kept', 'kept']],
  ['знати', ['know', 'knew', 'known']],
  ['вивчати', ['learn', 'learnt', 'learnt']],
  ['залишати', ['leave', 'left', 'left']],
  ['втрачати', ['lose', 'lost', 'lost']],
  ['зробити', ['make', 'made', 'made']],
  ['зустрічати', ['meet', 'met', 'met']],
  ['платити', ['pay', 'paid', 'paid']],
  ['класти', ['put', 'put', 'put']],
  ['читати', ['read', 'read', 'read']],
  ['їздити ::🎠::', ['ride', 'rode', 'ridden']],
  ['бігти', ['run', 'run', 'run']],
  ['сказати', ['say', 'said', 'said']],
  ['бачити', ['see', 'saw', 'seen']],
  ['продавати', ['sell', 'sold', 'sold']],
  ['відправляти', ['send', 'sent', 'sent']],
  ['закривати', ['shut', 'shut', 'shut']],
  ['співати', ['sing', 'sang', 'sung']],
  ['сидіти', ['sit', 'sat', 'sat']],
  ['спати', ['sleep', 'slept', 'slept']],
  ['говорити', ['speak', 'spoke', 'spoken']],
  ['витрачати, проводити час', ['spend', 'spent', 'spent']],
  ['стояти', ['stand', 'stood', 'stood']],
  ['красти', ['steal', 'stole', 'stolen']],
  ['плавати', ['swim', 'swam', 'swum']],
  ['брати', ['take', 'took', 'taken']],
  ['розповідати', ['tell', 'told', 'told']],
  ['думати', ['think', 'thought', 'thought']],
  ['розуміти', ['understand', 'understood', 'understood']],
  ['прокидатися', ['wake', 'woke', 'woken']],
  ['носити', ['wear', 'wore', 'worn']],
  ['перемагати', ['win', 'won', 'won']],
  ['писати', ['write', 'wrote', 'written']]
] as VerbModel[];
